baseURL = "https://sccm-zone.com/"
DefaultContentLanguage = "en"
languageCode = "en-us"
relativeURLs = false
title = "SCCM Zone"
theme = "beautifulhugo"
# metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Author]
    name = "Ioan Popovici"
    website = "SCCM-Zone.com"
    email = "hello@sccm-zone.com"
    github = "SCCM-Zone"
    twitter = "IoanPopovici"
    reddit = "Ioan_Popovici"
    linkedin = "IoanPopovici"
    paypal = "popoviciioan"   #RON popovicii/EUR popoviciioan
#   telegram = "IoanPopovici"

[blackfriday]
    extensions = ["hardLineBreak"]

[social]
    email = "hello@sccm-zone.com"
    twitter = "IoanPopovici"

[Params]
    #homeTitle = "Beautiful Hugo Theme"
    subtitle = "We ♡ configuration management and scripting"
    #logo = "uploads/authors/ioan_popovici.jpg" # Expecting square dimensions
    logo = "img/avatar-icon.png"
    favicon = "img/favicon.ico"
    dateFormat = "January 01, 2006"
    commit = false
    rss = true
    readingTime = true
    wordCount = false
    useHLJS = true
    socialShare = true
    delayDisqus = true
    showRelatedPosts = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[taxonomies]
    tag = "tags"
    category = "categories"
    site = "sites"

[[Params.bigimg]]
    src = "img/triangle.jpg"
#   desc = "Triangle"
    position = "center top"
[[Params.bigimg]]
    src = "img/sphere.jpg"
#   desc = "Sphere"
    position = "center top"
[[Params.bigimg]]
    src = "img/hexagon.jpg"
#   desc = "Hexagon"
    position = "center top"

[[menu.main]]
    name = "About"
    url = "pages/aboutus/"
    weight = 1

[[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = ""
    weight = 2

[[menu.main]]
    parent = "Blog"
    name = "Posts"
    url = "posts"
    weight = 1

[[menu.main]]
    parent = "Blog"
    name = "Tags"
    url = "tags"
    weight = 1

[[menu.main]]
    parent = "Blog"
    name = "Categories"
    url = "categories"
    weight = 2

[[menu.main]]
    parent = "Blog"
    name = "RSS"
    url = "posts/index.xml"
    weight = 2
[[menu.main]]
    name = "Authors"
    url = "authors"
    weight = 3
[[menu.main]]
    identifier = "Search"
    name = "Search"
    url = "search"
    weight = 4
